apiVersion: v1
kind: Namespace
metadata:
  name: quote
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quote
  namespace: quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/agentLogLevel: debug
        sidecar.istio.io/logLevel: debug
      labels:
        app: quote
    spec:
      containers:
        - name: backend
          image: docker.io/datawire/quote:0.5.0
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: quote
  annotations:
    a8r.io/description: "Quote of the moment service"
    a8r.io/owner: "No owner"
    a8r.io/chat: "#ambassador"
    a8r.io/bugs: "https://github.com/datawire/quote/issues"
    a8r.io/documentation: "https://github.com/datawire/quote/blob/master/README.md"
    a8r.io/repository: "https://github.com/datawire/quote"
    a8r.io/support: "http://a8r.io/Slack"
    a8r.io/runbook: "https://github.com/datawire/quote/blob/master/README.md"
    a8r.io/incidents: "https://github.com/datawire/quote/issues"
    a8r.io/dependencies: "None"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: quote
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote-backend
  namespace: quote
  labels:
    qotm: host
spec:
  prefix: /backend/
  service: https://quote.quote:80
  tls: upstream
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
    - quote.quote.svc.cluster.local
  http:
    - route:
        - destination:
            host: quote.quote.svc.cluster.local
            subset: v1
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: quote-rule
  namespace: quote
spec:
  host: quote.quote.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: 200ms
        maxConnections: 100
        tcpKeepalive:
          interval: 75s
          time: 300s
  subsets:
    - name: v1
      labels:
        app: quote
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: quote
spec:
  mtls:
    mode: STRICT
