image:
  repository: emissary.local/emissary
  tag: latest

replicaCount: 1
module: ''
createDefaultListeners: true

env:
  AMBASSADOR_ISTIO_SECRET_DIR: "/etc/istio-certs"
  AMBASSADOR_ENVOY_BASE_ID: "1"

podAnnotations:
  proxy.istio.io/config: |
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      OUTPUT_CERTS: /etc/istio-certs
      SECRET_TTL: 1m
  sidecar.istio.io/inject: "true"
  sidecar.istio.io/agentLogLevel: debug
  sidecar.istio.io/logLevel: debug
  sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
  traffic.sidecar.istio.io/includeInboundPorts: ""
  traffic.sidecar.istio.io/includeOutboundIPRanges: ""
volumeMounts:
  - mountPath: /etc/istio-certs/
    name: istio-certs
volumes:
  - name: istio-certs
    emptyDir:
      medium: Memory

livenessProbe:
  initialDelaySeconds: 5

readinessProbe:
  initialDelaySeconds: 5
